### ISSUE TITLE
Releases after 1.2.0

### ISSUE THREAD

**Issue by austek** [bizreach/play-zipkin-tracing#26]
Github releases page has several releases after 1.2.0 but I couldn't find any of them on MC or Sonatype. Are they actually released?

**Comment by takezoe** [comment]
Do you use Play 2.5 or before? In 1.3.0, we dropped support for Play 2.5 and before because it couldn't keep cross build for Scala versions by difference of supproted Scala versions between Play versions.

Currently, we maintain Play 2.6 and Akka support.
