### ISSUE TITLE
Scribe Support

### ISSUE THREAD

**Issue by knightpop** [bizreach/play-zipkin-tracing#28]
Do you have any plan to support scribe?

because Scribe is faster than normal HTTP

see: https://github.com/twitter/finagle/tree/develop/finagle-zipkin#data-sink

And also easy to integrate with Finagle-Zipin

**Comment by adriancole** [comment]
scribe is a deprecated transport, and an archived project by facebook
(archived years ago)

finagle retains scribe only for historical reasons. the current transports
are here https://github.com/openzipkin/zipkin-finagle

**Comment by adriancole** [comment]
PS if you are looking for transports that can easily work with play
tracing, there are ones here as well amazon and microsoft specific ones
https://github.com/openzipkin/zipkin-reporter-java

**Comment by knightpop** [comment]
Hmm... ok, I didn't notice that issue scribe is deprecated transport... thanks for the reply. Our team usually do Zipkin with Finatra. Thanks for replying me again!

**Comment by takezoe** [comment]
@adriancole Thanks for your quick support!
