### ISSUE TITLE
TraceWSRequest doubt

### ISSUE THREAD

**Issue by sachintyagi22** [bizreach/play-zipkin-tracing#33]
Hi, thanks for this. I was going through the code and I have a doubt.

In TraceWSRequest.execute() we start a child span before executing the underlying request. However, the underlying request itself can be a TraceWSRequest. 

This can happen if I do:
```implicit val traceData = ...
 val req = traceWSClient.url(spanName, url).withQueryString(params).withHttpHeaders(headers)
req.get()
```

In above case, it seems there will be multiple child spans (as many as there is nesting of TraceWSRequest) that will be started for a single request. Is this understanding correct? (I haven't yet tested this).

Thanks.

**Comment by takezoe** [comment]
`TraceWSRequest` isn't nested. It has just an instance of copied `WSRequest`. So it never generates multiple child soans in `execute()`.

**Comment by sachintyagi22** [comment]
Got it. Thanks.
